# 异常编码细节

## try/except/else 语句

注：在 Python 2.5 以后，`except` 和 `finally` 可以混在同一个 `try` 语句中。

```Python
try:
    <statements>
except <name1>:
    <statements>
except <name2, name3>:
    <statements>
except <name4> as <data>:
    <statements>
except:
    <statements>
else:  # 没有发生异常时触发的代码
    <statements>
```

### try 语句分句

`try` 语句分句形式：

|           分句形式           |                  说明                  |
|------------------------------|----------------------------------------|
| except:                      | 捕捉所有（其他）异常类型               |
| except name:                 | 只捕捉特定的异常                       |
| except name, value           | 捕捉所列的异常和其额外的数据（或实例） |
| except (name1, name2)        | 捕捉任何列出的异常                     |
| except (name1, name2), value | 捕捉任何列出的异常，并取得其额外数据   |
| else:                        | 如果没有触发异常，就运行               |
| finally                      | 总是会运行此代码块                     |

空的 `except` 语句很是方便，可以捕捉所有异常，但是也可能会捕捉和程序代码无关、意料之外的系统异常，而且可能拦截其他处理器的异常。解决方法：捕获一个名为 `Exception` 的异常，这几乎和空 `except` 语句相同，但是可以忽略与系统退出相关的异常。

```Python
try:
    pass
except Exception:
    pass
```

### try/else 分句

使用 `else` 语句，可以确定程序是否触发了异常。

### 例子：默认行为

默认的异常处理，可以提供有效的信息，了解问题所在。参考 `1、默认行为.py`

### 例子：捕捉内置异常

通过 `try/except` 语句，捕捉内置异常，并从内置异常中恢复程序。参考 `2捕获内置异常.py`

## try/finally 语句

程序没有触发异常：正常执行 `try` 语句中的代码，之后执行 `finally` 语句中的代码。

程序触发异常：执行 `finally` 语句中的代码，之后调用默认异常处理程序，打印信息，终止程序。（如果定义了可以恢复程序运行的异常处理程序，则会从上到下顺序运行，`finally` 中的代码最后运行）

### 例子：使用 try/finally 编写终止行为

参考 `3、终止行为.py` 最后一段

## 统一 try/except/finally 语句

参考 `4、统一语法.py`

从 Python 2.5 以后，可以将 `try/except/else/finally` 混合到一起。

### 统一 try 语句语法

必须要有 `try/except` 语句，`else` 和 `finally` 是可选项。

### 通过嵌套合并 finally 和 except

在 Python 2.5 之前，想要实现上述语法，需要进行嵌套，此处不予了解。

### 合并 try 例子

参考 `4、统一语法.py`

## raise 语句

```Python
raise <instance>  # 引发一个类实例
raise <class>  # 引发一个类
raise  # 引发最近引发的一个类
```

对于内置异常，下面两种方式都会引发指定异常的一个实例（第一种为隐式创建实例）

```Python
raise IndexError    # 使用类，隐式创建一个类实例
raise IndexError()  # 直接创建一个实例
```

也可以提前创建一个实例，如下所示：

```Python
exc = IndexError()
raise exc

exc = [IndexError(), TypeError]
raise exc[0]
```

### 利用 raise 传递异常

参考 `5、利用raise传递异常.py`

当一个异常被捕获后，就相当于死掉了，你无法再次获取或引发这个异常，但是通过 `raise` 语句，可以实现重复触发某个异常

### Python 3.0 异常链：raise from

参考 `6、raise form.py`

在 Python 3.0 中，允许 `raise` 语句拥有一个可选的 `from` 子句：`raise exception form otherexception`

当使用 `from` 时，第二个表达式指定了一个异常类型或实例，它会附加到引发异常的 `__cause__` 属性，如果该异常没有被捕获，则 Python 也会把该异常输出。

## assert 语句

`assert` 可以视为条件式的 `raise` 语句：

```Python
assert <test>, <data>
# 如果 <test> 计算结果为 False，则触发异常
```

执行起来类似于以下代码：

```Python
if __debug__:
    if not <test>:
        raise AssertionError(<data>)
```

### 例子：收集约束条件（但不是错误）

参考 `7、assert.py`

大部分时候，没有必要像例子中一样，使用 `assert` 语句检测约束条件。出问题的话，Python 都会有默认的解决方法。

## with/as 环境管理器

`with/as` 语句也用于定义必须执行的“终止”或“清理”行为，无论处理步骤中是否出现异常。

相比 `try/finally`，`with` 语句支持更多的基于对象的协议，可以为代码块定义支持进入和离开动作。

### 基本使用

```Python
with expressions[ as variable]:
    with-block

# 示例
with open(r'C:\misc\data') as myfile:
    for line in myfile:
        print(line)

# 等同于
myfile = open(r'C:\misc\data')
try:
    for line in myfile:
        print(line)
finally:
    myfile.close()
```

其中 `expressions` 语句需要返回一个对象，如果 `as` 语句存在，则将返回的对象赋值给变量 `variable`

环境管理器还可以用于多线程模块：

```Python
lock = threading.lock()
with lock:
    pass
```

例如之前讲过的 `decimal` 模块，也可以用环境管理器简化存储和保存当前小数的配置环境：

```Python
with decimal.localcontext() as ctx:
    ctx.prec = 2
    x = decimal.Decimal('1.00) / decimal.Decimal('3.00)
# 当这条语句运行后，当前线程的环境管理器状态自动恢复到语句开始之前的装填。
```

### 环境管理协议

参考 `8、环境管理器.py`

可以自己编写环境管理器，环境管理器的工作方式：

* 1、计算表达式，所得到的对象称为环境管理器，该对象必须有 `__enter__` 和 `__exit__` 方法
* 2、环境管理器的 `__enter__` 方法会被调用。如果 `as` 子句存在，其返回值会赋值给 `as` 子句后的变量，否则直接丢弃返回值
* 3、代码块中的嵌套代码也会执行
* 4、如果 `with` 代码块引发异常，则会调用 `__exit__(type, value, traceback)` 方法（带有异常细节）。
* 5、如果 `with` 代码块没有引发异常，依然会调用 `__exit__` 方法，其中的三个参数（`type`, `value`, `traceback`）将会以 `None` 传递

在 Python 3.1 后，`with/as` 结构可以指定多个环境管理器：

```Python
with A() as a, B() as b:
    pass

# 等同于
with A() as a:
    with B() as b:
        pass
```

## 本章小结
